feat: chip 컴포넌트 수정 반영
comento/comento-ui pull request #1167
Opened 2024-09-30 06:31 UTC by hananumber1

https://comento.agit.io/g/300257914/wall/347071764

1. color=primary, type=fill  배경 컬러 blue050으로 변경
2. color=error, type=fill 배경 컬러 red050으로 변경
3. 각 chip에 with icon 프로퍼티 추가 (none, left, right)
4. icon이 추가됨에 따라서, 좌,우,상,하 및 간격 여백 조정

2024-09-30 07:00 UTC, LuiGeeDev requested changes

2024-09-30 07:00 UTC, LuiGeeDev commented on src/components/chips/Chip.vue
> +		computedWithICon() {
P1: ICon으로 되어있네요

2024-09-30 07:01 UTC, LuiGeeDev commented
이거 크로매틱으로 스토리북 나오면 현정님께 다시 확인해보면 좋겠네요

2024-09-30 09:03 UTC, mong-byte commented on src/components/chips/Chip.vue
> +				return '';
@hananumber1 여기 빈 문자열이 들어가면 UI는 어떻게 나오게 되나요?
가능하다면 default상태를 정해두는건 어떨까 싶습니다.

2024-10-02 00:25 UTC, donghoon-song submitted a review, later dismissed

2024-10-04 05:42 UTC, hananumber1 commented on src/components/chips/Chip.vue
> +				return '';
문자열을 빈값으로 입력하면 기본 default chip으로 노출됩니다

2024-10-14 05:54 UTC, LuiGeeDev approved these changes

2024-10-14 05:54 UTC, merged